specVersion: 0.2.0
name: moonbeam-query-service
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x5c087aaf16a18a226c6935b8f946988857b947681dba8b3059a8c04b9cbfda7c'
  endpoint: wss://staging-polkadot-relay-rpc.parallel.fi
dataSources:
  - kind: substrate/Runtime
    startBlock: 246383
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleMoonbeamTermsSigned
          kind: substrate/CallHandler
        - handler: handleMoonbeamRewardAddress
          kind: substrate/CallHandler
